export const GET_TERMS = 'GET_TERMS';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';
export const GET_TERMS_ERROR = 'GET_TERMS_ERROR';

export const POST_GUEST_HOUSE_INFO = 'POST_GUEST_HOUSE_INFO';
export const POST_GUEST_HOUSE_INFO_SUCCESS = 'POST_GUEST_HOUSE_INFO_SUCCESS';
export const POST_GUEST_HOUSE_INFO_ERROR = 'POST_GUEST_HOUSE_INFO_ERROR';

export const CHECK_EMAIL = 'CHECK_EMAIL';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_ERROR = 'CHECK_EMAIL_ERROR';

export const CHECK_NAME = 'CHECK_NAME';
export const CHECK_NAME_SUCCESS = 'CHECK_NAME_SUCCESS';
export const CHECK_NAME_ERROR = 'CHECK_NAME_ERROR';

export const POST_CREATE_ACCOUNT = 'POST_CREATE_ACCOUNT';
export const POST_CREATE_ACCOUNT_SUCCESS = 'POST_CREATE_ACCOUNT_SUCCESS';
export const POST_CREATE_ACCOUNT_ERROR = 'POST_CREATE_ACCOUNT_ERROR';

export const REMOVE_CREATE_ACCOUNT_DATA = 'REMOVE_CREATE_ACCOUNT_DATA';
