export const GET_TERMS = 'GET_TERMS';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';
export const GET_TERMS_ERROR = 'GET_TERMS_ERROR';

export const POST_GUEST_HOUSE_INFO = 'POST_GUEST_HOUSE_INFO';
export const POST_GUEST_HOUSE_INFO_SUCCESS = 'POST_GUEST_HOUSE_INFO_SUCCESS';
export const POST_GUEST_HOUSE_INFO_ERROR = 'POST_GUEST_HOUSE_INFO_ERROR';
