const GET_TERMS = 'GET_TERMS';
const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';
const GET_TERMS_ERROR = 'GET_TERMS_ERROR';

const POST_GUEST_HOUSE_INFO = 'POST_GUEST_HOUSE_INFO';
const POST_GUEST_HOUSE_INFO_SUCCESS = 'POST_GUEST_HOUSE_INFO_SUCCESS';
const POST_GUEST_HOUSE_INFO_ERROR = 'POST_GUEST_HOUSE_INFO_ERROR';

const CHECK_EMAIL = 'CHECK_EMAIL';
const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
const CHECK_EMAIL_ERROR = 'CHECK_EMAIL_ERROR';

const CHECK_NAME = 'CHECK_NAME';
const CHECK_NAME_SUCCESS = 'CHECK_NAME_SUCCESS';
const CHECK_NAME_ERROR = 'CHECK_NAME_ERROR';

const POST_CREATE_ACCOUNT = 'POST_CREATE_ACCOUNT';
const POST_CREATE_ACCOUNT_SUCCESS = 'POST_CREATE_ACCOUNT_SUCCESS';
const POST_CREATE_ACCOUNT_ERROR = 'POST_CREATE_ACCOUNT_ERROR';

const REMOVE_CREATE_ACCOUNT_DATA = 'REMOVE_CREATE_ACCOUNT_DATA';

export {
  GET_TERMS,
  GET_TERMS_SUCCESS,
  GET_TERMS_ERROR,
  POST_GUEST_HOUSE_INFO,
  POST_GUEST_HOUSE_INFO_SUCCESS,
  POST_GUEST_HOUSE_INFO_ERROR,
  CHECK_EMAIL,
  CHECK_EMAIL_SUCCESS,
  CHECK_EMAIL_ERROR,
  CHECK_NAME,
  CHECK_NAME_SUCCESS,
  CHECK_NAME_ERROR,
  POST_CREATE_ACCOUNT,
  POST_CREATE_ACCOUNT_SUCCESS,
  POST_CREATE_ACCOUNT_ERROR,
  REMOVE_CREATE_ACCOUNT_DATA
};
