export const logInErrorCode = {
  NOT_FOUNT_ACCOUNT: 'US_002',
  INCORRECT_PASSWORD: 'US_006',
  DELETED_ACCOUNT: 'US_010',
  DISABLED_ACCOUNT: 'US_011',
  NOT_CERTIFIED_ACCOUNT: 'US_009',
  CERTIFIED_ACCOUNT: 'US_004'
};
