const POST_LOGIN = 'POST_LOGIN';
const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';

export { POST_LOGIN, POST_LOGIN_SUCCESS, POST_LOGIN_ERROR, REMOVE_ACCESS_TOKEN };
