export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

export const POST_RESEND_EMAIL = 'POST_RESEND_EMAIL';
export const POST_RESEND_EMAIL_SUCCESS = 'POST_RESEND_EMAIL_SUCCESS';
export const POST_RESEND_EMAIL_ERROR = 'POST_EMAIL_RESEND_ERROR';
